import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";
import PageLayout from "../components/PageLayout";
import GpsGate from "../components/GpsGate";
import MapTile from "../components/MapTile";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Sundial</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <GpsGate>
          <MapTile />
        </GpsGate>
      </PageLayout>
    </>
  );
};

export default Home;

