import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";
import PageLayout from "../components/PageLayout";
import GpsGate from "../components/GpsGate";
import MapTile from "../components/MapTile";
import { FC, useState } from "react";
import useLocation from "../utils/hooks/useLocation";
import SiteSearch from "../components/SiteSearch";
import { Site } from "@prisma/client";
import TimeClock from "../components/TimeClock";

const HomeMap: FC = () => {
  const { latitude, longitude } = useLocation();

  return <MapTile lat={latitude} lon={longitude} />;
}

const Home: NextPage = () => {
  const { data: session } = useSession();
  const [site, setSite] = useState<Site>();
  const [clockedIn, setClockedIn] = useState(false);

  function onSiteSelected(site: Site) {
    setSite(site);
  }

  return (
    <>
      <Head>
        <title>Sundial</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <GpsGate>
          <div className="flex flex-grow flex-col gap-4 p-4">
            <HomeMap />

            <SiteSearch onSelect={onSiteSelected} disabled={clockedIn} />

            {site && <TimeClock
              site={site}
              onClockedIn={() => {
                setClockedIn(true);
              }}
              onClockedOut={() => {
                setClockedIn(false);
              }}
            />}
          </div>
        </GpsGate>
      </PageLayout>
    </>
  );
};

export default Home;
